name: Build Android app

on:
  push:

jobs:
  build_android_app:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.1.0

      - name: Install tabris-cli
        run: npm install -g tabris-cli

      - name: Install application dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run --if-present prepare
          npm install

      - name: Setup java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 8

      - name: Uninstall build-tools 31.0.0
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --uninstall "build-tools;31.0.0"

      - name: Uninstall build-tools 33.0.1
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --uninstall "build-tools;33.0.1"

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Execute build
        env:
          TABRIS_BUILD_KEY: ${{ secrets.TABRIS_IOS_BUILD_KEY }}
        run: |
          tabris build --release android -- --packageType=bundle

      - name: Sign release app bundle
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDirectory: build/cordova/platforms/android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_APP_BUNDLE_SIGNING_KEY }}
          keyStorePassword: ${{ secrets.ANDROID_APP_BUNDLE_KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_APP_BUNDLE_KEY_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_APP_BUNDLE_KEY_PASSWORD }}

      - name: Store signed app bundle
        uses: actions/upload-artifact@v3.1.1
        with:
          name: signed-app-bundle
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
          retention-days: 7
